apiVersion: v1
kind: Secret
metadata:
  name: pgwatch-postgresql-secret-postgres
type: Opaque
stringData:
  password: 'beeF+u1bohce5xieZaamahChei3uthu>'
  username:  'postgres'
---

apiVersion: v1
kind: Secret
metadata:
  name: pgwatch-postgresql-secret-pgwatch
type: Opaque
stringData:
  password: 'awaes6ohR1dee2iedoo1n0Ao2lie3Le-'
  username:  'pgwatch'
---