{{- if eq .Values.pgwatch.postgres.create_metric_database "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: pgwatch-postgresql-secret-postgres
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: 'beeF+u1bohce5xieZaamahChei3uthu>'
  username:  'postgres'
---

apiVersion: v1
kind: Secret
metadata:
  name: pgwatch-postgresql-secret-pgwatch
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: 'awaes6ohR1dee2iedoo1n0Ao2lie3Le-'
  username:  'pgwatch'
---
{{ end }}